<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide" style="background-image:url('<?php echo $this->getSkinUrl('img/slide1.jpg'); ?>')"></div>
        <div class="swiper-slide" style="background-image:url('<?php echo $this->getSkinUrl('img/slide2.jpg'); ?>')"></div>
        <div class="swiper-slide" style="background-image:url('<?php echo $this->getSkinUrl('img/slide3.jpg'); ?>')"></div>
        <div class="swiper-slide" style="background-image:url('<?php echo $this->getSkinUrl('img/slide4.jpg'); ?>')"></div>
        </div>
</div>